/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetsIndexRouteImport } from './routes/vets/index'
import { Route as AdviceIndexRouteImport } from './routes/advice/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as VetSlugRouteImport } from './routes/vet/$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking/success'
import { Route as BookingIntakeRouteImport } from './routes/booking/intake'
import { Route as BookingConfirmRouteImport } from './routes/booking/confirm'
import { Route as AdviceSymptomCheckerRouteImport } from './routes/advice/symptom-checker'
import { Route as AdviceAskRouteImport } from './routes/advice/ask'
import { Route as AdviceSlugRouteImport } from './routes/advice/$slug'
import { Route as AccountPetsRouteImport } from './routes/account/pets'
import { Route as AccountConsultationsIndexRouteImport } from './routes/account/consultations/index'
import { Route as AdviceGuideSlugRouteImport } from './routes/advice/guide.$slug'
import { Route as AccountConsultationsConsultIdRouteImport } from './routes/account/consultations/$consultId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsIndexRoute = VetsIndexRouteImport.update({
  id: '/vets/',
  path: '/vets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceIndexRoute = AdviceIndexRouteImport.update({
  id: '/advice/',
  path: '/advice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetSlugRoute = VetSlugRouteImport.update({
  id: '/vet/$slug',
  path: '/vet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIntakeRoute = BookingIntakeRouteImport.update({
  id: '/booking/intake',
  path: '/booking/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmRoute = BookingConfirmRouteImport.update({
  id: '/booking/confirm',
  path: '/booking/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceSymptomCheckerRoute = AdviceSymptomCheckerRouteImport.update({
  id: '/advice/symptom-checker',
  path: '/advice/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceAskRoute = AdviceAskRouteImport.update({
  id: '/advice/ask',
  path: '/advice/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceSlugRoute = AdviceSlugRouteImport.update({
  id: '/advice/$slug',
  path: '/advice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPetsRoute = AccountPetsRouteImport.update({
  id: '/account/pets',
  path: '/account/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountConsultationsIndexRoute =
  AccountConsultationsIndexRouteImport.update({
    id: '/account/consultations/',
    path: '/account/consultations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdviceGuideSlugRoute = AdviceGuideSlugRouteImport.update({
  id: '/advice/guide/$slug',
  path: '/advice/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountConsultationsConsultIdRoute =
  AccountConsultationsConsultIdRouteImport.update({
    id: '/account/consultations/$consultId',
    path: '/account/consultations/$consultId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/pets': typeof AccountPetsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/advice/ask': typeof AdviceAskRoute
  '/advice/symptom-checker': typeof AdviceSymptomCheckerRoute
  '/booking/confirm': typeof BookingConfirmRoute
  '/booking/intake': typeof BookingIntakeRoute
  '/booking/success': typeof BookingSuccessRoute
  '/vet/$slug': typeof VetSlugRoute
  '/account/': typeof AccountIndexRoute
  '/advice/': typeof AdviceIndexRoute
  '/vets/': typeof VetsIndexRoute
  '/account/consultations/$consultId': typeof AccountConsultationsConsultIdRoute
  '/advice/guide/$slug': typeof AdviceGuideSlugRoute
  '/account/consultations/': typeof AccountConsultationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/pets': typeof AccountPetsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/advice/ask': typeof AdviceAskRoute
  '/advice/symptom-checker': typeof AdviceSymptomCheckerRoute
  '/booking/confirm': typeof BookingConfirmRoute
  '/booking/intake': typeof BookingIntakeRoute
  '/booking/success': typeof BookingSuccessRoute
  '/vet/$slug': typeof VetSlugRoute
  '/account': typeof AccountIndexRoute
  '/advice': typeof AdviceIndexRoute
  '/vets': typeof VetsIndexRoute
  '/account/consultations/$consultId': typeof AccountConsultationsConsultIdRoute
  '/advice/guide/$slug': typeof AdviceGuideSlugRoute
  '/account/consultations': typeof AccountConsultationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/pets': typeof AccountPetsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/advice/ask': typeof AdviceAskRoute
  '/advice/symptom-checker': typeof AdviceSymptomCheckerRoute
  '/booking/confirm': typeof BookingConfirmRoute
  '/booking/intake': typeof BookingIntakeRoute
  '/booking/success': typeof BookingSuccessRoute
  '/vet/$slug': typeof VetSlugRoute
  '/account/': typeof AccountIndexRoute
  '/advice/': typeof AdviceIndexRoute
  '/vets/': typeof VetsIndexRoute
  '/account/consultations/$consultId': typeof AccountConsultationsConsultIdRoute
  '/advice/guide/$slug': typeof AdviceGuideSlugRoute
  '/account/consultations/': typeof AccountConsultationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/pets'
    | '/advice/$slug'
    | '/advice/ask'
    | '/advice/symptom-checker'
    | '/booking/confirm'
    | '/booking/intake'
    | '/booking/success'
    | '/vet/$slug'
    | '/account/'
    | '/advice/'
    | '/vets/'
    | '/account/consultations/$consultId'
    | '/advice/guide/$slug'
    | '/account/consultations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/pets'
    | '/advice/$slug'
    | '/advice/ask'
    | '/advice/symptom-checker'
    | '/booking/confirm'
    | '/booking/intake'
    | '/booking/success'
    | '/vet/$slug'
    | '/account'
    | '/advice'
    | '/vets'
    | '/account/consultations/$consultId'
    | '/advice/guide/$slug'
    | '/account/consultations'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/pets'
    | '/advice/$slug'
    | '/advice/ask'
    | '/advice/symptom-checker'
    | '/booking/confirm'
    | '/booking/intake'
    | '/booking/success'
    | '/vet/$slug'
    | '/account/'
    | '/advice/'
    | '/vets/'
    | '/account/consultations/$consultId'
    | '/advice/guide/$slug'
    | '/account/consultations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountPetsRoute: typeof AccountPetsRoute
  AdviceSlugRoute: typeof AdviceSlugRoute
  AdviceAskRoute: typeof AdviceAskRoute
  AdviceSymptomCheckerRoute: typeof AdviceSymptomCheckerRoute
  BookingConfirmRoute: typeof BookingConfirmRoute
  BookingIntakeRoute: typeof BookingIntakeRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  VetSlugRoute: typeof VetSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdviceIndexRoute: typeof AdviceIndexRoute
  VetsIndexRoute: typeof VetsIndexRoute
  AccountConsultationsConsultIdRoute: typeof AccountConsultationsConsultIdRoute
  AdviceGuideSlugRoute: typeof AdviceGuideSlugRoute
  AccountConsultationsIndexRoute: typeof AccountConsultationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets/': {
      id: '/vets/'
      path: '/vets'
      fullPath: '/vets/'
      preLoaderRoute: typeof VetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/': {
      id: '/advice/'
      path: '/advice'
      fullPath: '/advice/'
      preLoaderRoute: typeof AdviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/$slug': {
      id: '/vet/$slug'
      path: '/vet/$slug'
      fullPath: '/vet/$slug'
      preLoaderRoute: typeof VetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/intake': {
      id: '/booking/intake'
      path: '/booking/intake'
      fullPath: '/booking/intake'
      preLoaderRoute: typeof BookingIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirm': {
      id: '/booking/confirm'
      path: '/booking/confirm'
      fullPath: '/booking/confirm'
      preLoaderRoute: typeof BookingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/symptom-checker': {
      id: '/advice/symptom-checker'
      path: '/advice/symptom-checker'
      fullPath: '/advice/symptom-checker'
      preLoaderRoute: typeof AdviceSymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/ask': {
      id: '/advice/ask'
      path: '/advice/ask'
      fullPath: '/advice/ask'
      preLoaderRoute: typeof AdviceAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/$slug': {
      id: '/advice/$slug'
      path: '/advice/$slug'
      fullPath: '/advice/$slug'
      preLoaderRoute: typeof AdviceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/pets': {
      id: '/account/pets'
      path: '/account/pets'
      fullPath: '/account/pets'
      preLoaderRoute: typeof AccountPetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/consultations/': {
      id: '/account/consultations/'
      path: '/account/consultations'
      fullPath: '/account/consultations/'
      preLoaderRoute: typeof AccountConsultationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/guide/$slug': {
      id: '/advice/guide/$slug'
      path: '/advice/guide/$slug'
      fullPath: '/advice/guide/$slug'
      preLoaderRoute: typeof AdviceGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/consultations/$consultId': {
      id: '/account/consultations/$consultId'
      path: '/account/consultations/$consultId'
      fullPath: '/account/consultations/$consultId'
      preLoaderRoute: typeof AccountConsultationsConsultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountPetsRoute: AccountPetsRoute,
  AdviceSlugRoute: AdviceSlugRoute,
  AdviceAskRoute: AdviceAskRoute,
  AdviceSymptomCheckerRoute: AdviceSymptomCheckerRoute,
  BookingConfirmRoute: BookingConfirmRoute,
  BookingIntakeRoute: BookingIntakeRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  VetSlugRoute: VetSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdviceIndexRoute: AdviceIndexRoute,
  VetsIndexRoute: VetsIndexRoute,
  AccountConsultationsConsultIdRoute: AccountConsultationsConsultIdRoute,
  AdviceGuideSlugRoute: AdviceGuideSlugRoute,
  AccountConsultationsIndexRoute: AccountConsultationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
