/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetsIndexRouteImport } from './routes/vets/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AdviceIndexRouteImport } from './routes/advice/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as VetSlugRouteImport } from './routes/vet/$slug'
import { Route as SubscribeProductIdRouteImport } from './routes/subscribe/$productId'
import { Route as ProductsCategoryRouteImport } from './routes/products/$category'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as BookingSuccessRouteImport } from './routes/booking/success'
import { Route as BookingIntakeRouteImport } from './routes/booking/intake'
import { Route as BookingConfirmRouteImport } from './routes/booking/confirm'
import { Route as AdviceSymptomCheckerRouteImport } from './routes/advice/symptom-checker'
import { Route as AdviceAskRouteImport } from './routes/advice/ask'
import { Route as AdviceSlugRouteImport } from './routes/advice/$slug'
import { Route as AccountSubscriptionsRouteImport } from './routes/account/subscriptions'
import { Route as AccountPetsRouteImport } from './routes/account/pets'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountConsultationsIndexRouteImport } from './routes/account/consultations/index'
import { Route as AdviceGuideSlugRouteImport } from './routes/advice/guide.$slug'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as AccountConsultationsConsultIdRouteImport } from './routes/account/consultations/$consultId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsIndexRoute = VetsIndexRouteImport.update({
  id: '/vets/',
  path: '/vets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceIndexRoute = AdviceIndexRouteImport.update({
  id: '/advice/',
  path: '/advice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetSlugRoute = VetSlugRouteImport.update({
  id: '/vet/$slug',
  path: '/vet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeProductIdRoute = SubscribeProductIdRouteImport.update({
  id: '/subscribe/$productId',
  path: '/subscribe/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIntakeRoute = BookingIntakeRouteImport.update({
  id: '/booking/intake',
  path: '/booking/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmRoute = BookingConfirmRouteImport.update({
  id: '/booking/confirm',
  path: '/booking/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceSymptomCheckerRoute = AdviceSymptomCheckerRouteImport.update({
  id: '/advice/symptom-checker',
  path: '/advice/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceAskRoute = AdviceAskRouteImport.update({
  id: '/advice/ask',
  path: '/advice/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceSlugRoute = AdviceSlugRouteImport.update({
  id: '/advice/$slug',
  path: '/advice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSubscriptionsRoute = AccountSubscriptionsRouteImport.update({
  id: '/account/subscriptions',
  path: '/account/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPetsRoute = AccountPetsRouteImport.update({
  id: '/account/pets',
  path: '/account/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountConsultationsIndexRoute =
  AccountConsultationsIndexRouteImport.update({
    id: '/account/consultations/',
    path: '/account/consultations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdviceGuideSlugRoute = AdviceGuideSlugRouteImport.update({
  id: '/advice/guide/$slug',
  path: '/advice/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/account/orders/$orderId',
  path: '/account/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountConsultationsConsultIdRoute =
  AccountConsultationsConsultIdRouteImport.update({
    id: '/account/consultations/$consultId',
    path: '/account/consultations/$consultId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/pets': typeof AccountPetsRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/advice/ask': typeof AdviceAskRoute
  '/advice/symptom-checker': typeof AdviceSymptomCheckerRoute
  '/booking/confirm': typeof BookingConfirmRoute
  '/booking/intake': typeof BookingIntakeRoute
  '/booking/success': typeof BookingSuccessRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/subscribe/$productId': typeof SubscribeProductIdRoute
  '/vet/$slug': typeof VetSlugRoute
  '/account/': typeof AccountIndexRoute
  '/advice/': typeof AdviceIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/vets/': typeof VetsIndexRoute
  '/account/consultations/$consultId': typeof AccountConsultationsConsultIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/advice/guide/$slug': typeof AdviceGuideSlugRoute
  '/account/consultations/': typeof AccountConsultationsIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/pets': typeof AccountPetsRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/advice/ask': typeof AdviceAskRoute
  '/advice/symptom-checker': typeof AdviceSymptomCheckerRoute
  '/booking/confirm': typeof BookingConfirmRoute
  '/booking/intake': typeof BookingIntakeRoute
  '/booking/success': typeof BookingSuccessRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/subscribe/$productId': typeof SubscribeProductIdRoute
  '/vet/$slug': typeof VetSlugRoute
  '/account': typeof AccountIndexRoute
  '/advice': typeof AdviceIndexRoute
  '/products': typeof ProductsIndexRoute
  '/vets': typeof VetsIndexRoute
  '/account/consultations/$consultId': typeof AccountConsultationsConsultIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/advice/guide/$slug': typeof AdviceGuideSlugRoute
  '/account/consultations': typeof AccountConsultationsIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/pets': typeof AccountPetsRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/advice/ask': typeof AdviceAskRoute
  '/advice/symptom-checker': typeof AdviceSymptomCheckerRoute
  '/booking/confirm': typeof BookingConfirmRoute
  '/booking/intake': typeof BookingIntakeRoute
  '/booking/success': typeof BookingSuccessRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/subscribe/$productId': typeof SubscribeProductIdRoute
  '/vet/$slug': typeof VetSlugRoute
  '/account/': typeof AccountIndexRoute
  '/advice/': typeof AdviceIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/vets/': typeof VetsIndexRoute
  '/account/consultations/$consultId': typeof AccountConsultationsConsultIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/advice/guide/$slug': typeof AdviceGuideSlugRoute
  '/account/consultations/': typeof AccountConsultationsIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/pets'
    | '/account/subscriptions'
    | '/advice/$slug'
    | '/advice/ask'
    | '/advice/symptom-checker'
    | '/booking/confirm'
    | '/booking/intake'
    | '/booking/success'
    | '/checkout/success'
    | '/product/$slug'
    | '/products/$category'
    | '/subscribe/$productId'
    | '/vet/$slug'
    | '/account/'
    | '/advice/'
    | '/products/'
    | '/vets/'
    | '/account/consultations/$consultId'
    | '/account/orders/$orderId'
    | '/advice/guide/$slug'
    | '/account/consultations/'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/pets'
    | '/account/subscriptions'
    | '/advice/$slug'
    | '/advice/ask'
    | '/advice/symptom-checker'
    | '/booking/confirm'
    | '/booking/intake'
    | '/booking/success'
    | '/checkout/success'
    | '/product/$slug'
    | '/products/$category'
    | '/subscribe/$productId'
    | '/vet/$slug'
    | '/account'
    | '/advice'
    | '/products'
    | '/vets'
    | '/account/consultations/$consultId'
    | '/account/orders/$orderId'
    | '/advice/guide/$slug'
    | '/account/consultations'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/pets'
    | '/account/subscriptions'
    | '/advice/$slug'
    | '/advice/ask'
    | '/advice/symptom-checker'
    | '/booking/confirm'
    | '/booking/intake'
    | '/booking/success'
    | '/checkout/success'
    | '/product/$slug'
    | '/products/$category'
    | '/subscribe/$productId'
    | '/vet/$slug'
    | '/account/'
    | '/advice/'
    | '/products/'
    | '/vets/'
    | '/account/consultations/$consultId'
    | '/account/orders/$orderId'
    | '/advice/guide/$slug'
    | '/account/consultations/'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountPetsRoute: typeof AccountPetsRoute
  AccountSubscriptionsRoute: typeof AccountSubscriptionsRoute
  AdviceSlugRoute: typeof AdviceSlugRoute
  AdviceAskRoute: typeof AdviceAskRoute
  AdviceSymptomCheckerRoute: typeof AdviceSymptomCheckerRoute
  BookingConfirmRoute: typeof BookingConfirmRoute
  BookingIntakeRoute: typeof BookingIntakeRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  SubscribeProductIdRoute: typeof SubscribeProductIdRoute
  VetSlugRoute: typeof VetSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdviceIndexRoute: typeof AdviceIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  VetsIndexRoute: typeof VetsIndexRoute
  AccountConsultationsConsultIdRoute: typeof AccountConsultationsConsultIdRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AdviceGuideSlugRoute: typeof AdviceGuideSlugRoute
  AccountConsultationsIndexRoute: typeof AccountConsultationsIndexRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets/': {
      id: '/vets/'
      path: '/vets'
      fullPath: '/vets/'
      preLoaderRoute: typeof VetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/': {
      id: '/advice/'
      path: '/advice'
      fullPath: '/advice/'
      preLoaderRoute: typeof AdviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/$slug': {
      id: '/vet/$slug'
      path: '/vet/$slug'
      fullPath: '/vet/$slug'
      preLoaderRoute: typeof VetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/$productId': {
      id: '/subscribe/$productId'
      path: '/subscribe/$productId'
      fullPath: '/subscribe/$productId'
      preLoaderRoute: typeof SubscribeProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/intake': {
      id: '/booking/intake'
      path: '/booking/intake'
      fullPath: '/booking/intake'
      preLoaderRoute: typeof BookingIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirm': {
      id: '/booking/confirm'
      path: '/booking/confirm'
      fullPath: '/booking/confirm'
      preLoaderRoute: typeof BookingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/symptom-checker': {
      id: '/advice/symptom-checker'
      path: '/advice/symptom-checker'
      fullPath: '/advice/symptom-checker'
      preLoaderRoute: typeof AdviceSymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/ask': {
      id: '/advice/ask'
      path: '/advice/ask'
      fullPath: '/advice/ask'
      preLoaderRoute: typeof AdviceAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/$slug': {
      id: '/advice/$slug'
      path: '/advice/$slug'
      fullPath: '/advice/$slug'
      preLoaderRoute: typeof AdviceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/subscriptions': {
      id: '/account/subscriptions'
      path: '/account/subscriptions'
      fullPath: '/account/subscriptions'
      preLoaderRoute: typeof AccountSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/pets': {
      id: '/account/pets'
      path: '/account/pets'
      fullPath: '/account/pets'
      preLoaderRoute: typeof AccountPetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/consultations/': {
      id: '/account/consultations/'
      path: '/account/consultations'
      fullPath: '/account/consultations/'
      preLoaderRoute: typeof AccountConsultationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/guide/$slug': {
      id: '/advice/guide/$slug'
      path: '/advice/guide/$slug'
      fullPath: '/advice/guide/$slug'
      preLoaderRoute: typeof AdviceGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/account/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/consultations/$consultId': {
      id: '/account/consultations/$consultId'
      path: '/account/consultations/$consultId'
      fullPath: '/account/consultations/$consultId'
      preLoaderRoute: typeof AccountConsultationsConsultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountPetsRoute: AccountPetsRoute,
  AccountSubscriptionsRoute: AccountSubscriptionsRoute,
  AdviceSlugRoute: AdviceSlugRoute,
  AdviceAskRoute: AdviceAskRoute,
  AdviceSymptomCheckerRoute: AdviceSymptomCheckerRoute,
  BookingConfirmRoute: BookingConfirmRoute,
  BookingIntakeRoute: BookingIntakeRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  SubscribeProductIdRoute: SubscribeProductIdRoute,
  VetSlugRoute: VetSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdviceIndexRoute: AdviceIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  VetsIndexRoute: VetsIndexRoute,
  AccountConsultationsConsultIdRoute: AccountConsultationsConsultIdRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AdviceGuideSlugRoute: AdviceGuideSlugRoute,
  AccountConsultationsIndexRoute: AccountConsultationsIndexRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
